meta_product_name: "contramarca"
meta_title: "contramarca - Independent stories for conscious readers"
meta_description: "Independent high-quality content. Journalists, artists, scientific platform that showcases multimedia content effectively and shares revenue with its members."

meta_image: "contramarca.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
